id: P006833
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:35.685731
source_metadata:
  id: bdr:W2PD17416
  title: ཐར་མདོ།
  author: ''
  volumes:
    c0950d1c1886457bb6bb10de8b4fc9cf:
      image_group_id: I4PD304
      title: ''
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
